// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/StealLikeBayes.h"
#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// orthogonal_complement_matrix_TW
arma::mat orthogonal_complement_matrix_TW(const arma::mat& x);
static SEXP _StealLikeBayes_orthogonal_complement_matrix_TW_try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(orthogonal_complement_matrix_TW(x));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_orthogonal_complement_matrix_TW(SEXP xSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_orthogonal_complement_matrix_TW_try(xSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// normalisation_wz2003_s
arma::rowvec normalisation_wz2003_s(const arma::mat& B, const arma::mat& B_hat_inv, const arma::mat& Sigma_inv, const arma::mat& diag_signs);
static SEXP _StealLikeBayes_normalisation_wz2003_s_try(SEXP BSEXP, SEXP B_hat_invSEXP, SEXP Sigma_invSEXP, SEXP diag_signsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B_hat_inv(B_hat_invSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_inv(Sigma_invSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type diag_signs(diag_signsSEXP);
    rcpp_result_gen = Rcpp::wrap(normalisation_wz2003_s(B, B_hat_inv, Sigma_inv, diag_signs));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_normalisation_wz2003_s(SEXP BSEXP, SEXP B_hat_invSEXP, SEXP Sigma_invSEXP, SEXP diag_signsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_normalisation_wz2003_s_try(BSEXP, B_hat_invSEXP, Sigma_invSEXP, diag_signsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// normalisation_wz2003
arma::cube normalisation_wz2003(arma::cube& posterior_B, const arma::mat& B_hat);
static SEXP _StealLikeBayes_normalisation_wz2003_try(SEXP posterior_BSEXP, SEXP B_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type posterior_B(posterior_BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B_hat(B_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(normalisation_wz2003(posterior_B, B_hat));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_normalisation_wz2003(SEXP posterior_BSEXP, SEXP B_hatSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_normalisation_wz2003_try(posterior_BSEXP, B_hatSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rgennorm
arma::cube rgennorm(const int n, arma::mat& X, const arma::cube& S_inv, const int& nu, const arma::field<arma::mat>& V, const bool normalise);
static SEXP _StealLikeBayes_rgennorm_try(SEXP nSEXP, SEXP XSEXP, SEXP S_invSEXP, SEXP nuSEXP, SEXP VSEXP, SEXP normaliseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type S_inv(S_invSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const bool >::type normalise(normaliseSEXP);
    rcpp_result_gen = Rcpp::wrap(rgennorm(n, X, S_inv, nu, V, normalise));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_rgennorm(SEXP nSEXP, SEXP XSEXP, SEXP S_invSEXP, SEXP nuSEXP, SEXP VSEXP, SEXP normaliseSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_rgennorm_try(nSEXP, XSEXP, S_invSEXP, nuSEXP, VSEXP, normaliseSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// qr_sign_cpp
arma::mat qr_sign_cpp(const arma::mat& A);
static SEXP _StealLikeBayes_qr_sign_cpp_try(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(qr_sign_cpp(A));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_qr_sign_cpp(SEXP ASEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_qr_sign_cpp_try(ASEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rhaar1
arma::mat rhaar1(const int& n);
static SEXP _StealLikeBayes_rhaar1_try(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rhaar1(n));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_rhaar1(SEXP nSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_rhaar1_try(nSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cholesky_tridiagonal
Rcpp::List cholesky_tridiagonal(const arma::vec& omega_diag, const double& omega_offdiag);
static SEXP _StealLikeBayes_cholesky_tridiagonal_try(SEXP omega_diagSEXP, SEXP omega_offdiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type omega_diag(omega_diagSEXP);
    Rcpp::traits::input_parameter< const double& >::type omega_offdiag(omega_offdiagSEXP);
    rcpp_result_gen = Rcpp::wrap(cholesky_tridiagonal(omega_diag, omega_offdiag));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_cholesky_tridiagonal(SEXP omega_diagSEXP, SEXP omega_offdiagSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_cholesky_tridiagonal_try(omega_diagSEXP, omega_offdiagSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// forward_algorithm
arma::vec forward_algorithm(const arma::vec& chol_diag, const arma::vec& chol_offdiag, const arma::vec& covector);
static SEXP _StealLikeBayes_forward_algorithm_try(SEXP chol_diagSEXP, SEXP chol_offdiagSEXP, SEXP covectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type chol_diag(chol_diagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type chol_offdiag(chol_offdiagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type covector(covectorSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_algorithm(chol_diag, chol_offdiag, covector));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_forward_algorithm(SEXP chol_diagSEXP, SEXP chol_offdiagSEXP, SEXP covectorSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_forward_algorithm_try(chol_diagSEXP, chol_offdiagSEXP, covectorSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// backward_algorithm
arma::vec backward_algorithm(const arma::vec& chol_diag, const arma::vec& chol_offdiag, const arma::vec& htmp);
static SEXP _StealLikeBayes_backward_algorithm_try(SEXP chol_diagSEXP, SEXP chol_offdiagSEXP, SEXP htmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type chol_diag(chol_diagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type chol_offdiag(chol_offdiagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type htmp(htmpSEXP);
    rcpp_result_gen = Rcpp::wrap(backward_algorithm(chol_diag, chol_offdiag, htmp));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_backward_algorithm(SEXP chol_diagSEXP, SEXP chol_offdiagSEXP, SEXP htmpSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_backward_algorithm_try(chol_diagSEXP, chol_offdiagSEXP, htmpSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rnorm1_precision_sampler
arma::vec rnorm1_precision_sampler(const arma::vec& location, const arma::vec& precision_diag, const double& precision_offdiag);
static SEXP _StealLikeBayes_rnorm1_precision_sampler_try(SEXP locationSEXP, SEXP precision_diagSEXP, SEXP precision_offdiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type location(locationSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type precision_diag(precision_diagSEXP);
    Rcpp::traits::input_parameter< const double& >::type precision_offdiag(precision_offdiagSEXP);
    rcpp_result_gen = Rcpp::wrap(rnorm1_precision_sampler(location, precision_diag, precision_offdiag));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_rnorm1_precision_sampler(SEXP locationSEXP, SEXP precision_diagSEXP, SEXP precision_offdiagSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_rnorm1_precision_sampler_try(locationSEXP, precision_diagSEXP, precision_offdiagSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// norm_rej
double norm_rej(const double a, const double b);
static SEXP _StealLikeBayes_norm_rej_try(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(norm_rej(a, b));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_norm_rej(SEXP aSEXP, SEXP bSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_norm_rej_try(aSEXP, bSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// unif_rej
double unif_rej(const double a, const double b);
static SEXP _StealLikeBayes_unif_rej_try(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(unif_rej(a, b));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_unif_rej(SEXP aSEXP, SEXP bSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_unif_rej_try(aSEXP, bSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// halfnorm_rej
double halfnorm_rej(const double a, const double b);
static SEXP _StealLikeBayes_halfnorm_rej_try(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(halfnorm_rej(a, b));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_halfnorm_rej(SEXP aSEXP, SEXP bSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_halfnorm_rej_try(aSEXP, bSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// exp_rej
double exp_rej(const double a, const double b);
static SEXP _StealLikeBayes_exp_rej_try(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_rej(a, b));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_exp_rej(SEXP aSEXP, SEXP bSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_exp_rej_try(aSEXP, bSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rtnormcpp
arma::vec rtnormcpp(const arma::vec& mean, const double sd, const arma::vec& lower, const arma::vec& upper);
static SEXP _StealLikeBayes_rtnormcpp_try(SEXP meanSEXP, SEXP sdSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnormcpp(mean, sd, lower, upper));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_rtnormcpp(SEXP meanSEXP, SEXP sdSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_rtnormcpp_try(meanSEXP, sdSEXP, lowerSEXP, upperSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rtmvnorm
arma::mat rtmvnorm(const arma::mat& mean, const arma::mat& sigma, const arma::mat& blc, const arma::mat& lower, const arma::mat& upper, const arma::mat& init, const arma::uword burn);
static SEXP _StealLikeBayes_rtmvnorm_try(SEXP meanSEXP, SEXP sigmaSEXP, SEXP blcSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP initSEXP, SEXP burnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type blc(blcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type burn(burnSEXP);
    rcpp_result_gen = Rcpp::wrap(rtmvnorm(mean, sigma, blc, lower, upper, init, burn));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_rtmvnorm(SEXP meanSEXP, SEXP sigmaSEXP, SEXP blcSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP initSEXP, SEXP burnSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_rtmvnorm_try(meanSEXP, sigmaSEXP, blcSEXP, lowerSEXP, upperSEXP, initSEXP, burnSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// validate_dimensions
void validate_dimensions(const Eigen::MatrixXd& cov, const Eigen::VectorXd& mean, const Eigen::VectorXd& initial, const Eigen::MatrixXd& F, const Eigen::VectorXd& g);
static SEXP _StealLikeBayes_validate_dimensions_try(SEXP covSEXP, SEXP meanSEXP, SEXP initialSEXP, SEXP FSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type g(gSEXP);
    validate_dimensions(cov, mean, initial, F, g);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_validate_dimensions(SEXP covSEXP, SEXP meanSEXP, SEXP initialSEXP, SEXP FSEXP, SEXP gSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_validate_dimensions_try(covSEXP, meanSEXP, initialSEXP, FSEXP, gSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// symmetrise
Eigen::MatrixXd symmetrise(const Eigen::MatrixXd& cov);
static SEXP _StealLikeBayes_symmetrise_try(SEXP covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cov(covSEXP);
    rcpp_result_gen = Rcpp::wrap(symmetrise(cov));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_symmetrise(SEXP covSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_symmetrise_try(covSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// transform_constraint_matrix
Eigen::MatrixXd transform_constraint_matrix(const Eigen::MatrixXd& F, const Eigen::MatrixXd& L);
static SEXP _StealLikeBayes_transform_constraint_matrix_try(SEXP FSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_constraint_matrix(F, L));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_transform_constraint_matrix(SEXP FSEXP, SEXP LSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_transform_constraint_matrix_try(FSEXP, LSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// transform_constraint_offset
Eigen::VectorXd transform_constraint_offset(const Eigen::MatrixXd& F, const Eigen::VectorXd& mean, const Eigen::VectorXd& g);
static SEXP _StealLikeBayes_transform_constraint_offset_try(SEXP FSEXP, SEXP meanSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_constraint_offset(F, mean, g));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_transform_constraint_offset(SEXP FSEXP, SEXP meanSEXP, SEXP gSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_transform_constraint_offset_try(FSEXP, meanSEXP, gSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// transform_initial_point
Eigen::VectorXd transform_initial_point(const Eigen::MatrixXd& L, const Eigen::VectorXd& mean, const Eigen::VectorXd& initial);
static SEXP _StealLikeBayes_transform_initial_point_try(SEXP LSEXP, SEXP meanSEXP, SEXP initialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type initial(initialSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_initial_point(L, mean, initial));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_transform_initial_point(SEXP LSEXP, SEXP meanSEXP, SEXP initialSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_transform_initial_point_try(LSEXP, meanSEXP, initialSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// get_next_linear_hit_time
Rcpp::List get_next_linear_hit_time(const Eigen::VectorXd& a, const Eigen::VectorXd& b, const Eigen::MatrixXd& F, const Eigen::VectorXd& g, int current_constraint);
static SEXP _StealLikeBayes_get_next_linear_hit_time_try(SEXP aSEXP, SEXP bSEXP, SEXP FSEXP, SEXP gSEXP, SEXP current_constraintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type current_constraint(current_constraintSEXP);
    rcpp_result_gen = Rcpp::wrap(get_next_linear_hit_time(a, b, F, g, current_constraint));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_get_next_linear_hit_time(SEXP aSEXP, SEXP bSEXP, SEXP FSEXP, SEXP gSEXP, SEXP current_constraintSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_get_next_linear_hit_time_try(aSEXP, bSEXP, FSEXP, gSEXP, current_constraintSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// verify_constraints
bool verify_constraints(const Eigen::VectorXd& x, const Eigen::MatrixXd& F, const Eigen::VectorXd& g);
static SEXP _StealLikeBayes_verify_constraints_try(SEXP xSEXP, SEXP FSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(verify_constraints(x, F, g));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_verify_constraints(SEXP xSEXP, SEXP FSEXP, SEXP gSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_verify_constraints_try(xSEXP, FSEXP, gSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// reflect_velocity
Eigen::VectorXd reflect_velocity(const Eigen::VectorXd& f, const Eigen::VectorXd& hit_velocity);
static SEXP _StealLikeBayes_reflect_velocity_try(SEXP fSEXP, SEXP hit_velocitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type f(fSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type hit_velocity(hit_velocitySEXP);
    rcpp_result_gen = Rcpp::wrap(reflect_velocity(f, hit_velocity));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_reflect_velocity(SEXP fSEXP, SEXP hit_velocitySEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_reflect_velocity_try(fSEXP, hit_velocitySEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sample_next
Eigen::VectorXd sample_next(const Eigen::VectorXd& current_sample, int dim, const Eigen::MatrixXd& F, const Eigen::VectorXd& g);
static SEXP _StealLikeBayes_sample_next_try(SEXP current_sampleSEXP, SEXP dimSEXP, SEXP FSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type current_sample(current_sampleSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_next(current_sample, dim, F, g));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_sample_next(SEXP current_sampleSEXP, SEXP dimSEXP, SEXP FSEXP, SEXP gSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_sample_next_try(current_sampleSEXP, dimSEXP, FSEXP, gSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rtmvnorm_hmc
Eigen::MatrixXd rtmvnorm_hmc(int n, const Eigen::VectorXd& mean, const Eigen::MatrixXd& cov, const Eigen::VectorXd& initial, const Eigen::MatrixXd& F, const Eigen::VectorXd& g, int burn);
static SEXP _StealLikeBayes_rtmvnorm_hmc_try(SEXP nSEXP, SEXP meanSEXP, SEXP covSEXP, SEXP initialSEXP, SEXP FSEXP, SEXP gSEXP, SEXP burnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    rcpp_result_gen = Rcpp::wrap(rtmvnorm_hmc(n, mean, cov, initial, F, g, burn));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_rtmvnorm_hmc(SEXP nSEXP, SEXP meanSEXP, SEXP covSEXP, SEXP initialSEXP, SEXP FSEXP, SEXP gSEXP, SEXP burnSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_rtmvnorm_hmc_try(nSEXP, meanSEXP, covSEXP, initialSEXP, FSEXP, gSEXP, burnSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sample_variances_horseshoe
arma::vec sample_variances_horseshoe(const arma::vec x, arma::vec& theta, double& zeta, arma::vec& nu, double& varpi);
static SEXP _StealLikeBayes_sample_variances_horseshoe_try(SEXP xSEXP, SEXP thetaSEXP, SEXP zetaSEXP, SEXP nuSEXP, SEXP varpiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double& >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double& >::type varpi(varpiSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_variances_horseshoe(x, theta, zeta, nu, varpi));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_sample_variances_horseshoe(SEXP xSEXP, SEXP thetaSEXP, SEXP zetaSEXP, SEXP nuSEXP, SEXP varpiSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_sample_variances_horseshoe_try(xSEXP, thetaSEXP, zetaSEXP, nuSEXP, varpiSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// sample_variances_normal_gamma
arma::vec sample_variances_normal_gamma(const arma::vec x, arma::vec& theta_tilde, double& zeta, double& a, const arma::vec a_vec, const double varrho0, const double varrho1, const bool hyper, const double tol);
static SEXP _StealLikeBayes_sample_variances_normal_gamma_try(SEXP xSEXP, SEXP theta_tildeSEXP, SEXP zetaSEXP, SEXP aSEXP, SEXP a_vecSEXP, SEXP varrho0SEXP, SEXP varrho1SEXP, SEXP hyperSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta_tilde(theta_tildeSEXP);
    Rcpp::traits::input_parameter< double& >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type a_vec(a_vecSEXP);
    Rcpp::traits::input_parameter< const double >::type varrho0(varrho0SEXP);
    Rcpp::traits::input_parameter< const double >::type varrho1(varrho1SEXP);
    Rcpp::traits::input_parameter< const bool >::type hyper(hyperSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_variances_normal_gamma(x, theta_tilde, zeta, a, a_vec, varrho0, varrho1, hyper, tol));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _StealLikeBayes_sample_variances_normal_gamma(SEXP xSEXP, SEXP theta_tildeSEXP, SEXP zetaSEXP, SEXP aSEXP, SEXP a_vecSEXP, SEXP varrho0SEXP, SEXP varrho1SEXP, SEXP hyperSEXP, SEXP tolSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_StealLikeBayes_sample_variances_normal_gamma_try(xSEXP, theta_tildeSEXP, zetaSEXP, aSEXP, a_vecSEXP, varrho0SEXP, varrho1SEXP, hyperSEXP, tolSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _StealLikeBayes_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::mat(*orthogonal_complement_matrix_TW)(const arma::mat&)");
        signatures.insert("arma::rowvec(*normalisation_wz2003_s)(const arma::mat&,const arma::mat&,const arma::mat&,const arma::mat&)");
        signatures.insert("arma::cube(*normalisation_wz2003)(arma::cube&,const arma::mat&)");
        signatures.insert("arma::cube(*rgennorm)(const int,arma::mat&,const arma::cube&,const int&,const arma::field<arma::mat>&,const bool)");
        signatures.insert("arma::mat(*qr_sign_cpp)(const arma::mat&)");
        signatures.insert("arma::mat(*rhaar1)(const int&)");
        signatures.insert("Rcpp::List(*cholesky_tridiagonal)(const arma::vec&,const double&)");
        signatures.insert("arma::vec(*forward_algorithm)(const arma::vec&,const arma::vec&,const arma::vec&)");
        signatures.insert("arma::vec(*backward_algorithm)(const arma::vec&,const arma::vec&,const arma::vec&)");
        signatures.insert("arma::vec(*rnorm1_precision_sampler)(const arma::vec&,const arma::vec&,const double&)");
        signatures.insert("double(*norm_rej)(const double,const double)");
        signatures.insert("double(*unif_rej)(const double,const double)");
        signatures.insert("double(*halfnorm_rej)(const double,const double)");
        signatures.insert("double(*exp_rej)(const double,const double)");
        signatures.insert("arma::vec(*rtnormcpp)(const arma::vec&,const double,const arma::vec&,const arma::vec&)");
        signatures.insert("arma::mat(*rtmvnorm)(const arma::mat&,const arma::mat&,const arma::mat&,const arma::mat&,const arma::mat&,const arma::mat&,const arma::uword)");
        signatures.insert("void(*validate_dimensions)(const Eigen::MatrixXd&,const Eigen::VectorXd&,const Eigen::VectorXd&,const Eigen::MatrixXd&,const Eigen::VectorXd&)");
        signatures.insert("Eigen::MatrixXd(*symmetrise)(const Eigen::MatrixXd&)");
        signatures.insert("Eigen::MatrixXd(*transform_constraint_matrix)(const Eigen::MatrixXd&,const Eigen::MatrixXd&)");
        signatures.insert("Eigen::VectorXd(*transform_constraint_offset)(const Eigen::MatrixXd&,const Eigen::VectorXd&,const Eigen::VectorXd&)");
        signatures.insert("Eigen::VectorXd(*transform_initial_point)(const Eigen::MatrixXd&,const Eigen::VectorXd&,const Eigen::VectorXd&)");
        signatures.insert("Rcpp::List(*get_next_linear_hit_time)(const Eigen::VectorXd&,const Eigen::VectorXd&,const Eigen::MatrixXd&,const Eigen::VectorXd&,int)");
        signatures.insert("bool(*verify_constraints)(const Eigen::VectorXd&,const Eigen::MatrixXd&,const Eigen::VectorXd&)");
        signatures.insert("Eigen::VectorXd(*reflect_velocity)(const Eigen::VectorXd&,const Eigen::VectorXd&)");
        signatures.insert("Eigen::VectorXd(*sample_next)(const Eigen::VectorXd&,int,const Eigen::MatrixXd&,const Eigen::VectorXd&)");
        signatures.insert("Eigen::MatrixXd(*rtmvnorm_hmc)(int,const Eigen::VectorXd&,const Eigen::MatrixXd&,const Eigen::VectorXd&,const Eigen::MatrixXd&,const Eigen::VectorXd&,int)");
        signatures.insert("arma::vec(*sample_variances_horseshoe)(const arma::vec,arma::vec&,double&,arma::vec&,double&)");
        signatures.insert("arma::vec(*sample_variances_normal_gamma)(const arma::vec,arma::vec&,double&,double&,const arma::vec,const double,const double,const bool,const double)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _StealLikeBayes_RcppExport_registerCCallable() { 
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_orthogonal_complement_matrix_TW", (DL_FUNC)_StealLikeBayes_orthogonal_complement_matrix_TW_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_normalisation_wz2003_s", (DL_FUNC)_StealLikeBayes_normalisation_wz2003_s_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_normalisation_wz2003", (DL_FUNC)_StealLikeBayes_normalisation_wz2003_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_rgennorm", (DL_FUNC)_StealLikeBayes_rgennorm_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_qr_sign_cpp", (DL_FUNC)_StealLikeBayes_qr_sign_cpp_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_rhaar1", (DL_FUNC)_StealLikeBayes_rhaar1_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_cholesky_tridiagonal", (DL_FUNC)_StealLikeBayes_cholesky_tridiagonal_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_forward_algorithm", (DL_FUNC)_StealLikeBayes_forward_algorithm_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_backward_algorithm", (DL_FUNC)_StealLikeBayes_backward_algorithm_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_rnorm1_precision_sampler", (DL_FUNC)_StealLikeBayes_rnorm1_precision_sampler_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_norm_rej", (DL_FUNC)_StealLikeBayes_norm_rej_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_unif_rej", (DL_FUNC)_StealLikeBayes_unif_rej_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_halfnorm_rej", (DL_FUNC)_StealLikeBayes_halfnorm_rej_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_exp_rej", (DL_FUNC)_StealLikeBayes_exp_rej_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_rtnormcpp", (DL_FUNC)_StealLikeBayes_rtnormcpp_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_rtmvnorm", (DL_FUNC)_StealLikeBayes_rtmvnorm_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_validate_dimensions", (DL_FUNC)_StealLikeBayes_validate_dimensions_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_symmetrise", (DL_FUNC)_StealLikeBayes_symmetrise_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_transform_constraint_matrix", (DL_FUNC)_StealLikeBayes_transform_constraint_matrix_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_transform_constraint_offset", (DL_FUNC)_StealLikeBayes_transform_constraint_offset_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_transform_initial_point", (DL_FUNC)_StealLikeBayes_transform_initial_point_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_get_next_linear_hit_time", (DL_FUNC)_StealLikeBayes_get_next_linear_hit_time_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_verify_constraints", (DL_FUNC)_StealLikeBayes_verify_constraints_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_reflect_velocity", (DL_FUNC)_StealLikeBayes_reflect_velocity_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_sample_next", (DL_FUNC)_StealLikeBayes_sample_next_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_rtmvnorm_hmc", (DL_FUNC)_StealLikeBayes_rtmvnorm_hmc_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_sample_variances_horseshoe", (DL_FUNC)_StealLikeBayes_sample_variances_horseshoe_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_sample_variances_normal_gamma", (DL_FUNC)_StealLikeBayes_sample_variances_normal_gamma_try);
    R_RegisterCCallable("StealLikeBayes", "_StealLikeBayes_RcppExport_validate", (DL_FUNC)_StealLikeBayes_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_StealLikeBayes_orthogonal_complement_matrix_TW", (DL_FUNC) &_StealLikeBayes_orthogonal_complement_matrix_TW, 1},
    {"_StealLikeBayes_normalisation_wz2003_s", (DL_FUNC) &_StealLikeBayes_normalisation_wz2003_s, 4},
    {"_StealLikeBayes_normalisation_wz2003", (DL_FUNC) &_StealLikeBayes_normalisation_wz2003, 2},
    {"_StealLikeBayes_rgennorm", (DL_FUNC) &_StealLikeBayes_rgennorm, 6},
    {"_StealLikeBayes_qr_sign_cpp", (DL_FUNC) &_StealLikeBayes_qr_sign_cpp, 1},
    {"_StealLikeBayes_rhaar1", (DL_FUNC) &_StealLikeBayes_rhaar1, 1},
    {"_StealLikeBayes_cholesky_tridiagonal", (DL_FUNC) &_StealLikeBayes_cholesky_tridiagonal, 2},
    {"_StealLikeBayes_forward_algorithm", (DL_FUNC) &_StealLikeBayes_forward_algorithm, 3},
    {"_StealLikeBayes_backward_algorithm", (DL_FUNC) &_StealLikeBayes_backward_algorithm, 3},
    {"_StealLikeBayes_rnorm1_precision_sampler", (DL_FUNC) &_StealLikeBayes_rnorm1_precision_sampler, 3},
    {"_StealLikeBayes_norm_rej", (DL_FUNC) &_StealLikeBayes_norm_rej, 2},
    {"_StealLikeBayes_unif_rej", (DL_FUNC) &_StealLikeBayes_unif_rej, 2},
    {"_StealLikeBayes_halfnorm_rej", (DL_FUNC) &_StealLikeBayes_halfnorm_rej, 2},
    {"_StealLikeBayes_exp_rej", (DL_FUNC) &_StealLikeBayes_exp_rej, 2},
    {"_StealLikeBayes_rtnormcpp", (DL_FUNC) &_StealLikeBayes_rtnormcpp, 4},
    {"_StealLikeBayes_rtmvnorm", (DL_FUNC) &_StealLikeBayes_rtmvnorm, 7},
    {"_StealLikeBayes_validate_dimensions", (DL_FUNC) &_StealLikeBayes_validate_dimensions, 5},
    {"_StealLikeBayes_symmetrise", (DL_FUNC) &_StealLikeBayes_symmetrise, 1},
    {"_StealLikeBayes_transform_constraint_matrix", (DL_FUNC) &_StealLikeBayes_transform_constraint_matrix, 2},
    {"_StealLikeBayes_transform_constraint_offset", (DL_FUNC) &_StealLikeBayes_transform_constraint_offset, 3},
    {"_StealLikeBayes_transform_initial_point", (DL_FUNC) &_StealLikeBayes_transform_initial_point, 3},
    {"_StealLikeBayes_get_next_linear_hit_time", (DL_FUNC) &_StealLikeBayes_get_next_linear_hit_time, 5},
    {"_StealLikeBayes_verify_constraints", (DL_FUNC) &_StealLikeBayes_verify_constraints, 3},
    {"_StealLikeBayes_reflect_velocity", (DL_FUNC) &_StealLikeBayes_reflect_velocity, 2},
    {"_StealLikeBayes_sample_next", (DL_FUNC) &_StealLikeBayes_sample_next, 4},
    {"_StealLikeBayes_rtmvnorm_hmc", (DL_FUNC) &_StealLikeBayes_rtmvnorm_hmc, 7},
    {"_StealLikeBayes_sample_variances_horseshoe", (DL_FUNC) &_StealLikeBayes_sample_variances_horseshoe, 5},
    {"_StealLikeBayes_sample_variances_normal_gamma", (DL_FUNC) &_StealLikeBayes_sample_variances_normal_gamma, 9},
    {"_StealLikeBayes_RcppExport_registerCCallable", (DL_FUNC) &_StealLikeBayes_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_StealLikeBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
